name: Build and Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ChrisThompsonTLDR/laravel-docit/.github/workflows/build-docs.yml@main
    with:
      docit-path: vendor/christhompsontldr/laravel-docit
      output-dir: docs/dist
      commit: false
      base-path: /laravel-runpod
    permissions:
      contents: write
      pages: write
      id-token: write
